#!/bin/bash
set -o errexit
if [ $# -ne 1 ] ; then
  echo "syntax: depdb-update FILE"
  exit 1
fi
BACKUP=$(dirname $1)/rosdep.yaml.$(date "+%F-%H-%M-%S")
echo "backing up your current rosdep.yaml file to $BACKUP"
cp $1 $BACKUP
echo "downloading the latest rosdep.yaml from sourceforge..."
wget -q http://ros.svn.sourceforge.net/svnroot/ros/trunk/tools/rosdep/rosdep.yaml -O $1
