#!/bin/bash
set -o errexit
if [ $# -lt 1 ] ; then
  echo "syntax: satisfy PACKAGE[S]"
  exit 1
fi
# first, try to generate the bash quietly. see if that craps out.
if ! rosdep generate_bash $* >/dev/null ; then
  # do it again, so that stdout can see what happened and errexit
  rosdep generate_bash $*
fi

# since that seemed to succeed, try to run it.
if bash <(rosdep generate_bash $*) ; then
  echo -e "\n[rosdep]: success\n"
else
  echo -e "\n[rosdep]: failure\n"
fi
