include $(shell rospack find mk)/cmake.mk

# OUT = ../../bin/master
# OUT2 = ../../bin/zenmaster
# 
# default: $(OUT)
# 
# $(OUT): nodes/master 
# 	cp nodes/master $(OUT)
# 	cp nodes/master $(OUT2)
# 
# clean:
# 	-rm $(OUT)
# 	-rm src/rospy/*.pyc
# 	-rm scripts/*.pyc

