"""autogenerated by genmsg_py from Clock.msg. Do not edit."""
import roslib.message
import struct

import roslib.rostime

import warnings
warnings.warn("roslib/Clock argument is deprecated. Please use rosgraph_msgs/Clock instead", DeprecationWarning, stacklevel=3)

class Clock(roslib.message.Message):
  _md5sum = "a9c97c1d230cfc112e270351a944ee47"
  _type = "roslib/Clock"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# roslib/Clock is used for publishing simulated time in ROS. 
# This message simply communicates the current time.
# For more information, see http://www.ros.org/wiki/Clock
time clock

"""
  __slots__ = ['clock']
  _slot_types = ['time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       clock
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Clock, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.clock is None:
        self.clock = roslib.rostime.Time()
    else:
      self.clock = roslib.rostime.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2I.pack(_x.clock.secs, _x.clock.nsecs))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.clock is None:
        self.clock = roslib.rostime.Time()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.clock.secs, _x.clock.nsecs,) = _struct_2I.unpack(str[start:end])
      self.clock.canon()
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2I.pack(_x.clock.secs, _x.clock.nsecs))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.clock is None:
        self.clock = roslib.rostime.Time()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.clock.secs, _x.clock.nsecs,) = _struct_2I.unpack(str[start:end])
      self.clock.canon()
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2I = struct.Struct("<2I")
