#!/bin/bash

pkgs=`rospack list-names`

vcs=
for p in $pkgs; do
  vc=`rospack vcs0 $p | sed 's/type: svn.*url: \([ ]*\)/\1/g'`
  for v in $vc; do
    vcs+=$v
    vcs+=' '
  done
done

for v in $vcs; do
  echo p | svn info $v
done
