#!/bin/bash
xterm -e "source ~/.bashrc && rosrun roscpp_tutorials talker" &
xterm -e "source ~/.bashrc && rosrun roscpp_tutorials listener chatter:=chatter_throttle" &
# this will make it drop 2 out of 3 messages
#valgrind rosrun topic_tools throttle chatter 50 1
valgrind ./throttle chatter 50 1
