if(EXISTS ${CMAKE_CURRENT_BINARY_DIR}/package.cmake)
  include(${CMAKE_CURRENT_BINARY_DIR}/package.cmake)
endif()
include_directories(include/message_filters)
rosbuild_add_boost_directories()
rosbuild_add_library(message_filters src/connection.cpp)
rosbuild_link_boost(message_filters thread signals)
#rosbuild_add_executable(filter_example src/filter_example.cpp)
#target_link_libraries(filter_example message_filters)
add_subdirectory(test EXCLUDE_FROM_ALL)
rosbuild_add_rostest(test/time_sequencer_unittest.xml)
rosbuild_add_rostest(test/test_subscriber.xml)

