if(EXISTS ${CMAKE_CURRENT_BINARY_DIR}/package.cmake)
  include(${CMAKE_CURRENT_BINARY_DIR}/package.cmake)
endif()
rosbuild_add_rostest(test/params_basic.test)
rosbuild_add_rostest(test/env.test)
rosbuild_add_rostest(test/roslaunch.test)
rosbuild_add_pyunit(test/test_core.py)
rosbuild_add_pyunit(test/test_nodeprocess.py)
rosbuild_add_pyunit(test/test_xmlloader.py)
rosbuild_add_pyunit(test/test_roslaunch_child.py)
rosbuild_add_pyunit(test/test_roslaunch_dump_params.py)
rosbuild_add_pyunit(test/test_roslaunch_node_args.py)
rosbuild_add_pyunit(test/test_roslaunch_launch.py)
rosbuild_add_pyunit(test/test_roslaunch_parent.py)
rosbuild_add_pyunit(test/test_roslaunch_pmon.py)
rosbuild_add_pyunit(test/test_roslaunch_remote.py)
rosbuild_add_pyunit(test/test_roslaunch_server.py)
rosbuild_add_pyunit(test/test_roslaunch_rlutil.py)
rosbuild_add_pyunit(test/test_version.py)

