#!/bin/bash

SBCL_CMD=`rospack find sbcl`/scripts/run-sbcl.sh
if [[ $# == 4 ]]; then
  pkg=$1
  system=$2
  entry=$3
  output=$4
  $SBCL_CMD --noinform --end-runtime-options --no-userinit --noprint --disable-debugger --load `rospack find roslisp`/scripts/make-roslisp-exec.lisp $pkg :$system $entry > $output.lisp
  cat > $output <<EOF
#!/bin/bash
ROSLISP_CURRENT_PACKAGE=$pkg $SBCL_CMD --noinform --end-runtime-options --noprint --no-userinit --disable-debugger --load $output.lisp --end-toplevel-options \$*
EOF
  chmod a+x $output
else
    echo "Usage: make_node_exec <pkg> <system> <entry> <output>"
    exit 1
fi
