#!/usr/bin/env bash

set -e 

if (( $# == 2 ))
then
    PKG=`rospack find $1`
    FILENAME=$PKG/msg/$2.msg
    rosrun genmsg_cpp genmsg_lisp $FILENAME
    rosrun roslisp genmsg_lisp.py $FILENAME

    NAME="$2.lisp"
    echo "  $NAME"
    diff -w $PKG/msg/lisp/$1/$NAME $PKG/msg_gen/lisp/$NAME | head -n 50

    NAME="_package_$2.lisp"
    echo "  $NAME"
    diff -w $PKG/msg/lisp/$1/$NAME $PKG/msg_gen/lisp/$NAME | head -n 50
    
    NAME=".$2.asd-dep"
    echo "  $NAME"
    F1=`mktemp`
    F2=`mktemp`
    sort $PKG/msg/lisp/$1/.$2.asd-dep > $F1
    sort $PKG/msg_gen/lisp/.$2.asd-dep > $F2
    diff -w $F1 $F2  | head -n 50
    
elif (( $# == 1 ))
then
    for p in `rosmsg package $1`
    do args=`echo $p | tr "/" " "`
       echo $p
       $0 $args
    done
    PKG=`rospack find $1`
    # diff -w $PKG/msg/lisp/$1/_package.lisp $PKG/msg_gen/lisp/_package.lisp | head -n 50
    # diff -w $PKG/msg/lisp/$1/$1-msg.asd $PKG/msg_gen/lisp/$1-msg.asd | head -n 50

else
    echo "Usage: test-genmsg-lisp PKG MSG or test-genmsg-lisp PKG"
    exit 1
fi

