Header header
# start angle of the scan [rad]
float32 angle_min
# end angle of the scan [rad]
float32 angle_max
# angular distance between measurements [rad]
float32 angle_increment
# time between measurements
float32 time_increment
# time between scans
float32 scan_time
# minimum range value [m]
float32 range_min
# maximum range value [m]
float32 range_max
# range data [m]
float32[] ranges
# intensity data [device-specific units]
float32[] intensities
