/* auto-generated by gensrv_java from /home/kwc/ros/test/test_ros/srv/AddTwoInts.srv.  Do not edit! */
package ros.pkg.test_ros.srv;

import java.nio.ByteBuffer;

public class AddTwoInts extends ros.communication.Service<AddTwoInts.Request, AddTwoInts.Response> 
{

public static String __s_getDataType() { return "test_ros/AddTwoInts"; }
public static String __s_getMD5Sum() { return "6a2e34150c00229791cc89ff309fff21"; }

public String getDataType() { return AddTwoInts.__s_getDataType(); }
public String getMD5Sum() { return AddTwoInts.__s_getMD5Sum(); }

public static class Request extends ros.communication.Message
{

  public long a;
  public long b;

  public Request() {
 super();

  }
  public static java.lang.String __s_getDataType() { return "test_ros/AddTwoIntsRequest"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "int64 a\n" + 
    "int64 b\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("6a2e34150c00229791cc89ff309fff21"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("test_ros/AddTwoInts"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Request clone() {
    Request clone = (Request)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("a", "long");
     m.put("b", "long");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Request)) throw new RuntimeException("Invalid Type");
    Request __m2 = (Request) __m;
    a = __m2.a;
    b = __m2.b;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += 8; // a
    __l += 8; // b
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    bb.putLong(a);
    bb.putLong(b);
  }
  public void deserialize(ByteBuffer bb)  {
    a = bb.getLong();
    b = bb.getLong();
  }
}

public static class Response extends ros.communication.Message
{

  public long sum;

  public Response() {
 super();

  }
  public static java.lang.String __s_getDataType() { return "test_ros/AddTwoIntsResponse"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "int64 sum\n" + 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("6a2e34150c00229791cc89ff309fff21"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("test_ros/AddTwoInts"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Response clone() {
    Response clone = (Response)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("sum", "long");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Response)) throw new RuntimeException("Invalid Type");
    Response __m2 = (Response) __m;
    sum = __m2.sum;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += 8; // sum
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    bb.putLong(sum);
  }
  public void deserialize(ByteBuffer bb)  {
    sum = bb.getLong();
  }
}

public AddTwoInts.Request createRequest() { return new AddTwoInts.Request(); }public AddTwoInts.Response createResponse() { return new AddTwoInts.Response(); }}

