#!/bin/bash
# run from test_roscpp/ 
for((i=0;$i<1000;i=$(($i+1))));do
  TOPIC=$RANDOM
  let "TOPIC %= 10"
  ./bin/dos_botherder chatter:=$TOPIC __name:=$RANDOM &
  TOPIC=$RANDOM
  let "TOPIC %= 10"
  ./bin/dos_subscriber chatter:=$TOPIC __name:=$RANDOM &
  sleep 0.01
done
rm *.log
