/* auto-generated by genmsg_cpp from msg/String.msg.  Do not edit! */
package ros.pkg.rosjava_test.msg;


import java.nio.ByteBuffer;

public  class String extends ros.communication.Message
{

  public java.lang.String data;

  public String() {
 super();
    data = new java.lang.String();

  }
  public static java.lang.String __s_getDataType() { return "rosjava/String"; }
  public static java.lang.String __s_getMD5Sum() { return "5b89344b4d080ca499c0648063c40738"; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "string data\n" + 
    "\n" + 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public String clone() {
    String clone = (String)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("data", "java.lang.String");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof String)) throw new RuntimeException("Invalid Type");
    String __m2 = (String) __m;
    data = __m2.data;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += 4 + data.length(); // data
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, data);
  }
  public void deserialize(ByteBuffer bb) {
    data = Serialization.readString(bb);
  }
}

